apiVersion: v1
kind: Pod
metadata:
  name: theme-copy-pod
  namespace: prod
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: /mnt/themes
          name: theme-storage
  volumes:
    - name: theme-storage
      persistentVolumeClaim:
        claimName: whometa-theme
